trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  name: 'Default'

variables:
  NODE_VERSION: '22.x'

stages:
- stage: Build
  displayName: 'Build Frontend'
  jobs:
  - job: Build
    displayName: 'Build and Deploy'
    steps:

    # 🟢 Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '$(NODE_VERSION)'
      displayName: 'Install Node.js'

    # 🧹 Clear npm cache
    - script: |
        cd frontend
        npm cache clean --force
        echo "npm cache cleared"
      displayName: 'Clear npm Cache'
      shell: powershell

    # 📦 Install dependencies
    - script: |
        cd frontend
        npm ci
        echo "Dependencies installed"
      displayName: 'Install Dependencies'
      shell: powershell

    # 🛠️ Build frontend
    - script: |
        cd frontend
        npm run build
        echo "Frontend build completed successfully"
      displayName: 'Build Frontend'
      shell: powershell
      env:
        VITE_AUTHORITY: $(VITE_AUTHORITY)
        VITE_CLIENT_ID: $(VITE_CLIENT_ID)
        VITE_REDIRECT_URI: $(VITE_REDIRECT_URI)
        VITE_SERVER_URL: $(VITE_SERVER_URL)
        NODE_ENV: production
        CI: true

    # 🚀 Deploy to Azure Static Web App
    - task: AzureStaticWebApp@0
      inputs:
        app_location: 'frontend'
        output_location: 'dist'
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      displayName: 'Deploy to Azure Static Web App'