name: Backend Deploy to Azure Web App

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    environment: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build backend
      run: |
        cd backend
        npm run build
        
    - name: Prepare deployment package
      run: |
        cd backend
        # Create a deployment package with all necessary files
        mkdir -p ../deploy-package
        cp -r dist ../deploy-package/
        cp package.json ../deploy-package/
        cp package-lock.json ../deploy-package/
        cp -r templates ../deploy-package/
        cp -r node_modules ../deploy-package/
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deploy-package
